All:
	g++ -O3 -o test_handler test_handler.cpp JunctionHandler.cpp SpliceWay.cpp SamRec.cpp sharedlib.cpp AlignmentHandler.cpp JunctionSeed.cpp FusionSamRec.cpp UnionExpressedRegions.cpp disjointset.cpp -lpthread 2>log

